#ansible_python_interpreter: "/usr/bin/python3.6"
# this is the path at which any local configurations are saved to
config:
  directory: "/tmp/hapi-configs"
certificates:
  country:
    code: "CA"
  state:
    code: "QC"
    full: "Quebec"
  city: "Montreal"
  Organization: "BCE"
  Organizational_Unit: "WNOC"
  expiration: "8760h"
  encryption:
    algorithm: "rsa"
    size: 2048
kubernetes:
  version: "1.8.2"
  accessIP: "192.168.0.65"
  cluster:
    shortName: "hapi"
    name: "hapi.novalocal"
    domain: "hapi.localdomain"
    podCIDR: "10.200.0.0/16"
    serviceCIDR: "10.32.0.0/24"
    dns: "10.32.0.10"
    serviceIP: "10.32.0.1"
  cni:
    version: "0.6.0"
  romana:
    version: "2.0-preview.3"
    podCIDR: "10.200.0.0/22"
    blockMask: 29
    serviceIP: "10.32.0.99"
    etcd:
      serviceIP: "10.32.0.88"
  # must be 32 chars
  encryptionKey: "E92kQnLJZwUyVfA6Qf9AlM2b1x9O8fx2"
  etcd:
    version: "3.2.9"
    database:
      path: "/var/lib/etcd"
  rook:
    hostConfigPath: "/rook/conf"
    hostStoragePath: "/rook/data"
icn_settings:
  http_proxy: "http://142.117.128.41:80"
  https_proxy: "http://142.117.128.41:80"
  no_proxy: "localhost,127.0.0.1,.novalocal,192.168.0.56,192.168.0.57,192.168.0.58,192.168.0.59,192.168.0.60,192.168.0.61,192.168.0.62,192.168.0.63,192.168.0.64,192.168.0.65,wnoc-etc-1,wnoc-etc-2,wnoc-etc-3,wnoc-etc-1.novalocal,wnoc-etc-2.novalocal,wnoc-etc-3.novalocal,wnoc-kubemaster-1,wnoc-kubemaster-2,wnoc-kubemaster-3,wnoc-kubemaster-1.novalocal,wnoc-kubemaster-2.novalocal,wnoc-kubemaster-3.novalocal,wnoc-kube-1,wnoc-kube-1.novalocal,wnoc-kube-2,wnoc-kube-2.novalocal,wnoc-kube-3,wnoc-kube-3.novalocal,lb,lb.novalocal"

server_settings:
  paths: "/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin"
 
ntp_servers:
  server0: "172.25.166.66"
  server1: "172.25.155.225"