- name: generate the configurations
  template:
    src: kube-proxy.csr.json.j2
    dest: "{{ config.directory }}/certs/configs/kube-proxy.csr.json"

- name: generate the kube-proxy cert
  shell: "cfssl gencert -ca=./ca.pem -ca-key=./ca-key.pem -config=../configs/config.json -profile=kubernetes ../configs/kube-proxy.csr.json | cfssljson -bare kube-proxy"
  args:
    chdir: "{{ config.directory }}/certs/outputs"
