- name: copy CA.pem to node
  become: yes
  copy:
    src: "{{ config.directory }}/certs/outputs/ca.pem"
    dest: "/etc/pki/ca-trust/source/anchors/ca.pem"
    mode: 0700
  
- name: update CA trust store
  shell: /usr/bin/update-ca-trust
  become: yes