- name: download kube-controller-manager from provisioner and make sure it's executable
  become: yes
  copy:
   src: "{{ config.directory }}/bin/kube-controller-manager"
   dest: /usr/local/bin/
   mode: 0700

- name: restart the service
  become: yes
  service:
    name: kube-controller-manager
    state: restarted
