- name: check to see if the kube-scheduler binary exists
  become: yes
  stat:
    path: /usr/local/bin/kube-scheduler
  register: kube_scheduler_binary

- name: download and extract
  become: yes
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes.version }}/bin/linux/amd64/kube-scheduler"
    dest: /usr/local/bin/
  when: not kube_scheduler_binary.stat.exists

- name: make sure it's executable
  become: yes
  file:
    path: /usr/local/bin/kube-scheduler
    mode: "u+rwx"
  when: not kube_scheduler_binary.stat.exists
