- name: check to see if the kube-scheduler binary exists
  become: yes
  stat:
    path: /usr/local/bin/kube-scheduler
  register: kube_scheduler_binary

- name: download kube-scheduler from provisioner and make sure it's executable
  become: yes
  copy:
   src: "{{ config.directory }}/bin/kube-scheduler"
   dest: /usr/local/bin/
   mode: 0700
  when: not kube_scheduler_binary.stat.exists

