- name: Create rook mount directories
  become: yes
  file:
    path: "{{item}}"
    state: directory
  with_items:
  - "/rook"
  - "/rook/conf"
  

# - name: Mount up device by label
  # become: yes
  # mount:
    # path: /rook/conf
    # src: LABEL=rook-conf
    # fstype: ext4
    # state: mounted 

# - name: Mount up device by label
  # become: yes
  # mount:
    # path: /rook/conf
    # src: LABEL=rook-data
    # fstype: ext4
    # state: mounted     