- name: check to see if the kube-proxy binary exists
  become: yes
  stat:
    path: /usr/local/bin/kube-proxy
  register: kube_proxy_binary

- name: download and extract
  become: yes
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes.version }}/bin/linux/amd64/kube-proxy"
    dest: /usr/local/bin/
  when: not kube_proxy_binary.stat.exists

- name: make sure it's executable
  become: yes
  file:
    path: /usr/local/bin/kube-proxy
    mode: "u+rwx"
  when: not kube_proxy_binary.stat.exists
