- name: check to see if the kube-proxy binary exists
  become: yes
  stat:
    path: /usr/local/bin/kube-proxy
  register: kube_proxy_binary
  
- name: download kube-proxy from provisioner and make sure it's executable
  become: yes
  copy:
   src: "{{ config.directory }}/bin/kube-proxy"
   dest: /usr/local/bin/
   mode: 0700
  when: not kube_proxy_binary.stat.exists
