- name: download kubelet from provisioner and make sure it's executable
  become: yes
  copy:
   src: "{{ config.directory }}/bin/kubelet"
   dest: /usr/local/bin/
   mode: 0700

- name: restart the service
  become: yes
  service:
    name: kubelet
    state: restarted
