- name: generate the romana spec
  template:
    src: "{{ item }}.yaml.j2"
    dest: "{{ config.directory }}/k8s/specs/{{ item }}.yaml"
  with_items:
  - rook.operator
  - rook.cluster
  - rook.storageclass
  - rook.toolbox
