- name: create an kubelet service file for each k8s master
  template:
    src: kubelet.service.j2
    dest: "{{ config.directory }}/services/kubelet.master.{{ item.1 }}.service"
  with_indexed_items: "{{ groups['kubernetes-masters'] }}"
