- name: check to see if the docker binary exists
  become: yes
  stat:
    path: /usr/bin/docker
  register: docker_binary

- name: Remove old Docker deps
  become: yes
  yum:
    name: "{{ item }}"
    state: absent
    update_cache: yes
  with_items:
  - docker-common-2:1.12.6-61.git85d7426.el7.centos.x86_64
  


- name: add the docker rpm_key
  become: yes
  rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg
    validate_certs: no
    
  
- name: Download Docker CE repository conf
  become: yes
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    validate_certs: no
  
- name: Create a systemd drop-in directory for the docker service
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0700
    
- name: Configure docker proxy settings
  become: yes
  template:
    src: "https-proxy.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/https-proxy.conf"

- name: Install Docker
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - docker-ce
  
- name: Start docker
  become: yes
  service:
    name: docker
    state: started
