- name: check to see if the docker binary exists
  become: yes
  stat:
    path: /usr/bin/docker
  register: docker_binary

- name: add the docker apt-key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: not docker_binary.stat.exists

- name: get the release
  become: yes
  command: lsb_release -cs
  register: release
  when: not docker_binary.stat.exists

- name: add the docker apt repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable"
    state: present
  when: not docker_binary.stat.exists

- name: install docker
  become: yes
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: not docker_binary.stat.exists
