- name: copy the kubelet rbac spec to each node
  become: yes
  copy:
    src: "{{ config.directory }}/k8s/specs/kubelet.rbac.yaml"
    dest: /tmp/kubelet.rbac.yaml

- name: run the kubelet rbac spec
  become: yes
  shell: "/usr/local/bin/kubectl create -f /tmp/kubelet.rbac.yaml"
  register: kubelet_rbac_spec_result
  failed_when: "'created' not in kubelet_rbac_spec_result.stdout and 'already exists' not in kubelet_rbac_spec_result.stderr"
