- name: check to see if the kubelet binary exists
  become: yes
  stat:
    path: /usr/local/bin/kubelet
  register: kubelet_binary

- name: download kubelet from provisioner and make sure it's executable
  become: yes
  copy:
   src: "{{ config.directory }}/bin/kubelet"
   dest: /usr/local/bin/
   mode: 0700
  when: not kubelet_binary.stat.exists
