- name: check to see if the kubectl binary exists
  become: yes
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl_binary

- name: download kubectl from provisioner and make sure it's executable
  become: yes
  copy:
   src: "{{ config.directory }}/bin/kubectl"
   dest: /usr/local/bin/
   mode: 0700
  when: not kubectl_binary.stat.exists
